config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :rooms, only: [:index, :show] do
    resources :messages, only: :create
    resources :surveys, only: :create
  end

  resources :surveys, only: [] do
    resources :answers, only: :create
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/allrooms', to: 'base#index'
      post '/surveys', to: 'base#create'
      get '/surveys/results', to: 'base#display_results'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
  has_many :room_interests
  has_many :interests, through: :room_interests
  has_many :surveys
  has_many :room_topics
  has_many :topics, through: :room_topics

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: :show
  before_action :set_entities, only: :show

  def index
    @rooms = Room.all
    if params[:query].present?
      sql = " \
    rooms.name @@ :query \
    OR interests.name @@ :query \
    "
      @rooms = Room.joins(:interests).where(sql, query: "%#{params[:query]}%").distinct
    else
      @rooms = Room.all
    end
  end

  def show
    @ongoing_survey = @room.surveys.where(status: "open")
    @closed_surveys = @room.surveys.where(status: "closed")
    @users_in_room = []
    @room.online_users.each do |user|
      @users_in_room << User.find(user)
    end
    @topics = @room.messages.where(message_type: 'topic')
    @topics_pending = @topics.select do |topic|
      topic.created_at > Time.zone.now - 10.minutes
    end
    @end_timer_in_seconds = ((@topics_pending.first.created_at + 10.minutes) - Time.zone.now).round unless @topics_pending.empty?
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def set_entities
    @survey = Survey.new
    @message = Message.new
    @answer = Answer.new
  end
end

app/views/rooms/_show_new_topic.html.erb
<div class="expand">
<!-- Button new topic -->
  <div id="two-button">
          <!-- Button trigger modal -->
    <button id="new-survey-btn" class="expand-button">
      <i class="fas fa-poll" style="font-size: 2rem"></i>
      Lancer un sondage
    </button>

    <button id="new-topic-btn" class="expand-button">
      <i class="fas fa-bullhorn" style="font-size: 2rem"></i>
      Proposer un sujet
    </button>
  </div>
  <div class="expand-content-topic">
    <%= simple_form_for [room, message], remote: true do |f| %>
      <%= hidden_field_tag :message_type, "topic" %>
      <% topics_array=[] %>
      <% room.topics.each { |topic| topics_array << topic.subject } %>
      <%= f.input :content,
                    as: :radio_buttons,
                    collection_wrapper_tag: 'div',
                    collection_wrapper_class: 'category-wrapper',
                    item_wrapper_class: 'category-item',
                    input_html: {class: 'category-selector'},
                    collection: topics_array %>
      <%# <div class="button-field"> %>
      <%= f.button :submit, "Proposer", id: 'expand-btn', class: 'button-field' %>
      <%# </div> %>
    <% end %>
  </div>
  <div class="expand-content-survey mb-3">
    <div id="survey-content">
      <div class="modal-body">
        <%= simple_form_for [ @room, @survey ] do |f| %>
          <%= f.input :title, label: 'Question :', placeholder: "Votre question...", input_html: { autocomplete: 'off' } %>
          <div class="d-flex justify-content-between mb-5">
            <div class="d-flex flex-column survey-column">
              <%= f.input :first_proposition, label: 'Option 1 :', placeholder: "Option 1...", class:"flex-grow-1 mb-2", input_html: { id: 'input1', autocomplete: 'off'}  %>
              <%# f.input :first_photo, as: :file, label: false, input_html: { class: 'd-none', id: 'photo-input1' }, label_html: { class: 'upload-photo'}, label: '<i class="fas fa-camera"></i> <br> Télécharger une photo'.html_safe %>
              <%= image_tag "", width: 300, class: "hidden photo-preview-all", id: "photo-preview1" %>
              <%= f.input :url_first_image, as: :hidden, input_html: { id: 'url-input1' } %>

            </div>
            <div class="d-flex flex-column survey-column">
              <%= f.input :second_proposition, label: 'Option 2 :', placeholder: "Option 2...", input_html: { id: 'input2', autocomplete: 'off' }%>
              <%# f.input :second_photo, as: :file, label: false, input_html: { class: 'd-none', id: 'photo-input2' }, label_html: { class: 'upload-photo'}, label: '<i class="fas fa-camera"></i> <br> Télécharger une photo'.html_safe %>
              <%= image_tag "", width: 300, class: "hidden photo-preview-all", id: "photo-preview2" %>
              <%= f.input :url_second_image, as: :hidden, input_html: { id: 'url-input2' } %>
            </div>
          </div>
          <%= f.submit "Lancer le sondage", class: 'btn btn-create-survey' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_show_ongoing_survey.html.erb
<div class="ongoing-survey">
  <div id="survey-<%= survey.id %>" class="survey-container">
    <h5 class='text-center'><%= survey.title %></h5>
    <% unless survey.answers.find_by(user: current_user) %>
      <div class="ongoing-vote">
        <%= render 'rooms/show_ongoing_survey_vote', survey: survey %>
      </div>
    <% end %>
    <div class="ongoing-result">
      <%= render 'rooms/show_ongoing_survey_results', survey: survey %>
    </div>
  </div>
</div>

app/views/rooms/_show_ongoing_survey_results.html.erb
<div class="result-wrap">
  <div class="d-flex justify-content-between">
    <div class="first-text"><%= survey.first_proposition.capitalize %> : <span class="first-prop-count"><%= survey.first_proposition_count %></span></div>
    <div class="second-text"><%= survey.second_proposition.capitalize %> : <span class="second-prop-count"><%= survey.second_proposition_count %></span></div>
  </div>

  <div class="results-poll">
    <div class="proposition first" style="width: <%= survey.first_proposition_percent %>%">
    </div>
    <div class="proposition second" style="width: <%= survey.second_proposition_percent %>%">
    </div>
  </div>
    <div id='winning-prop-survey<%= survey.id %>'>
    </div>
</div>

app/views/rooms/_show_ongoing_survey_vote.html.erb
<%= simple_form_for [ survey, Answer.new ], remote: true do |f| %>
    <div class="answers-wrapper">
      <input type="hidden" name="answer[selected_proposition]" value="" />
      <div class="answer-item">
        <input class="answer-selector" type="radio" value="<%= survey.first_proposition %>" name="answer[selected_proposition]" id="answer_selected_proposition_1" />
        <label for="answer_selected_proposition_1" id="answer1" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= survey.first_photo.present? ? cl_image_path(survey.first_photo.key) : 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1500&q=80' %>);">
          <div id="proposition-text">
            <p><%= survey.first_proposition.capitalize %></p>
          </div>
        </label>
      </div>
      <div class="answer-item">
        <input class="answer-selector" type="radio" value="<%= survey.second_proposition %>" name="answer[selected_proposition]" id="answer_selected_proposition_2" />
        <label for="answer_selected_proposition_2" id="answer2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= survey.second_photo.present? ? cl_image_path(survey.second_photo.key) : 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1500&q=80' %>);">
          <div id="proposition-text">
            <p><%= survey.second_proposition.capitalize %></p>
          </div>
        </label>
      </div>
    </div>
  <%= f.button :submit, "Voter", id: 'vote-btn', class: 'button-field' %>
<% end %>

app/views/rooms/index.html.erb
<%= render 'shared/navbar' %>

<div id="page-container">
  <div id="content-wrap">
    <div class="container first-part">
      <div id="search-index">
        <%= form_tag rooms_path, method: :get do %>
          <div class="d-flex align-items-center">
            <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Rechercher un thème...",
                autocomplete: 'off'
            %>
            <button type="submit" class="btn search-btn">
              <i class='fas fa-search'></i>
            </button>
          </div>
        <% end %>
      </div>
      <%= link_to "< Retourner à l'accueil", root_path, class: 'back-link' %>
      <p class="mt-3 mb-0"><%= @rooms.length %> <%= "room".pluralize(@rooms.length) %> <%= "correspond".pluralize(@rooms.length) %> à votre recherche</p>
      <div class="card-container">
        <% @rooms.each do |room| %>
          <%= render 'shared/room_card', room: room %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/rooms/show.html.erb
<div class="main-page">
  <aside class="sidebar">
    <div class = "upper-left-room">
      <div class="d-flex justify-content-between">
        <div class="d-flex">
          <%= link_to "", root_path, class:"exit-logo" %>
          <div class="ml-2 custom-width">
            <h4><%= @room.name %></h4>
            <p><%= @room.description %></p>
          </div>
        </div>
        <div>
          <span><%= pluralize(@users_in_room.count, "chinner")%></span>
          <div class="d-flex online-users flex-row-reverse">
            <% @users_in_room.first(4).each do |user| %>
              <%= cl_image_tag user.photo.key, class: "online-users-avatar" %>
            <% end %>
          </div>
        </div>
      </div>
      <br>
      <div class="topic-banner">
        <p> <span class="blinking">🔴</span>
        Sujet en cours : <br> <span id="topic-banner-anchor"><%= @room.messages.where(message_type: "topic").last ? @room.messages.where(message_type: "topic").last.content : "Aucun sujet en cours." %></span>
        </p>
        <div id="countdown" <%= "data-end-timer=#{@end_timer_in_seconds}" if @end_timer_in_seconds %>>
        </div>
      </div>
    </div>

    <%# Sondage et topic %>
    <section class="room-topic">
      <%= render 'rooms/show_new_topic', room: @room, message: @message %>
    </section>
    <section class="room-survey">
      <div class="expand">
        <div id="survey-container">
          <% if @ongoing_survey %>
            <% @ongoing_survey.each do |survey| %>
              <%= render 'rooms/show_ongoing_survey', survey: survey %>
            <% end %>
          <% end %>
        </div>
      </div>
    </section>
  </aside>
  <div id="chat">
    <div id="scroll">
      <div id="messages" data-chatroom-id="<%= @room.id %>">
        <% @room.messages.each do |message| %>
          <% if message.message_type == 'message' %>
            <%= render "messages/message", message: message %>
          <% else  %>
            <%= render "messages/announce", message: message %>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= simple_form_for [ @room, @message ], remote: true do |f| %>
      <%= hidden_field_tag :message_type, "message" %>
      <%= f.input :content, autofocus: true, label: false, placeholder: "Taper votre message...", input_html: { id: 'chat-bar', autocomplete: 'off' } %>
    <% end %>
  </div>
</div>